version: "3.6"
services:
  php:
    container_name: "php-${PROJECT_NAME}"
    environment:
    - APP_ENV=test
    - APP_SECRET=${APP_SECRET}
    - DB_NAME=${DB_NAME}
    - DB_PASS=${DB_PASS}
    - DB_USER=${DB_USER}
    - JWT_PASSPHRASE=${JWT_PASSPHRASE}
    - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    - JWT_TOKEN_TTL=${JWT_TOKEN_TTL}
    - MAILER_URL=${MAILER_URL}
    - CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    depends_on:
      - nginx
      - db
    networks:
      - backend
  db:
    image: mysql:5.7
    container_name: "db-${PROJECT_NAME}"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "7dd8c4284984a2e9"
      MYSQL_DATABASE: qit
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: "7dd8c4284984a2e0"
    networks:
      - backend
    ports:
      - "3306:3306"
    expose:
      - 3306
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: "nginx-${PROJECT_NAME}"
    expose:
      - 80
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - backend
networks:
   backend:
volumes:
   db-data: ~
