version: "3.6"
services:
  php:
    container_name: "php-${PROJECT_NAME}"
#    environment:
#    - APP_ENV=test
#    - APP_SECRET=${APP_SECRET}
#    - DB_NAME=${DB_NAME}
#    - DB_PASS=${DB_PASS}
#    - DB_USER=${DB_USER}
#    - JWT_PASSPHRASE=${JWT_PASSPHRASE}
#    - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
#    - JWT_SECRET_KEY=${JWT_SECRET_KEY}
#    - JWT_TOKEN_TTL=${JWT_TOKEN_TTL}
#    - MAILER_URL=${MAILER_URL}
#    - CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}
#    - XDEBUG_CONFIG="remote_host=127.0.0.1 remote_enable=1"
#    - XDEBUG_CONFIG="remote_host=192.168.220.1 remote_enable=1"
#    - PHP_IDE_CONFIG="serverName=Docker"
#    env_file: .env
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.110"
      PHP_IDE_CONFIG: "serverName=Docker"
      APP_ENV: "test"
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
#      - ${PROJECT_NAME}-codesync:/var/www/webapp:rw
      - .:/var/www/webapp:rw,cached
#      - uploads:/var/www/webapp/uploads:rw,cached
#      - ${PROJECT_NAME}-codesync:/var/www/webapp
    depends_on:
      - nginx
      - db
    networks:
      - backend
    expose:
      - 9001

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    container_name: "db-${PROJECT_NAME}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "7dd8c4284984a2e9"
      MYSQL_DATABASE: qit
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: "7dd8c4284984a2e0"
    networks:
      - backend
    ports:
      - "3306:3306"
    expose:
      - 3306
  nginx:
    container_name: "nginx-${PROJECT_NAME}"
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    expose:
      - 80
    ports:
      - "80:80"
      - "443:443"
    restart: always
#    volumes:
#       - ${PROJECT_NAME}-codesync:/var/www/webapp:ro
#       - ${PROJECT_NAME}-codesync:/var/www/webapp
    networks:
      - backend
networks:
   backend:
volumes:
  db-data: ~
#  uploads:
#    external: true
#  qit-codesync:
#    external: true
